create or replace TRIGGER VERSAO_TRIGGER
BEFORE UPDATE ON VERSAO 
FOR EACH ROW
BEGIN
    IF :new.NRO_VERSAO <> :old.NRO_VERSAO THEN
        INSERT INTO AUD_VERSAO VALUES (AUD_VERSAO_SEQ.nextval, :new.COD_VERSAO, 'NRO_VERSAO', :old.NRO_VERSAO, :new.NRO_VERSAO, null);
    END IF;

    IF :new.DAT_VERSAO <> :old.DAT_VERSAO THEN
        INSERT INTO AUD_VERSAO VALUES (AUD_VERSAO_SEQ.nextval, :new.COD_VERSAO, 'DAT_VERSAO', :old.DAT_VERSAO, :new.DAT_VERSAO, null);
    END IF;
    
    IF :new.IND_LIBERADO <> :old.IND_LIBERADO THEN
        INSERT INTO AUD_VERSAO VALUES (AUD_VERSAO_SEQ.nextval, :new.COD_VERSAO, 'IND_LIBERADO', :old.IND_LIBERADO, :new.IND_LIBERADO, null);
    END IF;
    
    IF :new.IND_SITUACAO <> :old.IND_SITUACAO THEN
        INSERT INTO AUD_VERSAO VALUES (AUD_VERSAO_SEQ.nextval, :new.COD_VERSAO, 'IND_SITUACAO', :old.IND_SITUACAO, :new.IND_SITUACAO, null);
    END IF;
END;